# Generated by Django 6.1 on 2026-09-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_license_number', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField(blank=True)),
                ('visit_fee', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('visit_duration', models.PositiveIntegerField(default=30, help_text='duration of each visit in minutes(like: 20, 30, 60)')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='doctor/avatars/')),
            ],
            options={
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='specialty title')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WorkingShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'SATURDAY'), (1, 'SUNDAY'), (2, 'MONDAY'), (3, 'TUESDAY'), (4, 'WEDNESDAY'), (5, 'THURSDAY'), (6, 'FRIDAY')], verbose_name='Weekday')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
            ],
            options={
                'verbose_name': 'Working shift',
                'verbose_name_plural': 'Working shifts',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
